### ISSUE TITLE
plugins

### ISSUE THREAD

**Issue by rursi** [Hetachi/SDONATE-SELF-HOSTED-SERVER-FILES#1]
Hello i have sdonate license but i lost my plugins folder.U have plugins .cs files?
And this is latest sdonate version?

where is install.php? if u need I can upload install.php file

**Comment by Hetachi** [comment]
Yes, I actually still do have them, will update repo with the plugins, but I only have csgo plugin.

**Comment by Hetachi** [comment]
#006d11d

**Comment by Hetachi** [comment]
Added the csgo plugin in #1
Let me know if the issue is resolved.

**Comment by rursi** [comment]
oh i need rust plugin

**Comment by Hetachi** [comment]
Sadly I do not have the rust plugin anymore. I will try to find it, but it's a really slim chance.

**Comment by Hetachi** [comment]
Thanks to you I have updated repo and added missing files as resolution to issue #3
