### ISSUE TITLE
install.php

### ISSUE THREAD

**Issue by rursi** [Hetachi/SDONATE-SELF-HOSTED-SERVER-FILES#2]
This is install.php file . Before install open and edit admin and password lines then u can install script more info in official doc.This script create database tables etc.

[sdonate_install.zip](https://github.com/Hetachi/SDONATE-SELF-HOSTED-SERVER-FILES/files/5900615/sdonate_install.zip)

**Comment by Hetachi** [comment]
Thanks I will add it to the codebase
