### ISSUE TITLE
latest stable version

### ISSUE THREAD

**Issue by rursi** [Hetachi/SDONATE-SELF-HOSTED-SERVER-FILES#3]
Ok i get latest stable version (1.9.11) with all plugins,install etc.I drop files here.
[sdonate- 1.9.11.zip](https://github.com/Hetachi/SDONATE-SELF-HOSTED-SERVER-FILES/files/5916986/sdonate-.1.9.11.zip)

**Comment by Hetachi** [comment]
Awesome thank you so much! 
I have added in this commit: #3
